#!/usr/bin/env php
<?php

/**
 * This file is part of Dana\Interpolator.
 *
 * @author  dana <dana@dana.is>
 * @license MIT
 */

require_once __DIR__ . '/../src/Interpolator.php';

use Dana\Interpolator\Interpolator;

if ( $argc < 3 ) {
	fprintf(
		\STDERR,
		"usage: %s <fixtures> <string> ...\n",
		basename($argv[0])
	);
	fprintf(\STDERR, "\n");
	fprintf(
		\STDERR,
		"%-8s  %s\n",
		'fixtures',
		'JSON-encoded array or dictionary of fixtures'
	);
	fprintf(
		\STDERR,
		"%-8s  %s\n",
		'string',
		'One or more strings to interpolate'
	);
	fprintf(
		\STDERR,
		"\nexample: %s '[\"world\"]' 'Hello, %%{0}!' 'Goodbye, %%{0|u}!'\n",
		basename($argv[0])
	);
	exit(1);
}

try {
	$fixtures     = trim($argv[1]) === '' ? [] : json_decode($argv[1], true);
	$interpolator = new Interpolator();

	foreach ( array_slice($argv, 2) as $string ) {
		fprintf(
			\STDOUT,
			"%s -> %s\n",
			$string,
			rtrim($interpolator->render($string, $fixtures), "\r\n")
		);
	}
} catch ( \Exception $e ) {
	fprintf(
		\STDERR,
		"%s: %s (%s:%d)\n",
		get_class($e),
		$e->getMessage(),
		basename($e->getFile()),
		$e->getLine()
	);
	exit(1);
}

exit(0);

